In [3]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from sklearn.preprocessing import OrdinalEncoder
# import dataprep.eda.create_report as report
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

In [5]:
dataset = pd.read_csv(r'C:\Users\ags-008\Downloads\each_ball_records.csv')
df = pd.DataFrame(dataset)
df

,match_no,ballnumber,inningno,over,outcome,batter,bowler,comment,score
0,1,1,1,0.1,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
1,1,2,1,0.2,1lb,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, 1 leg bye,",1
2,1,3,1,0.3,0,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, no run,",0
3,1,4,1,0.4,1,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, 1 run,",1
4,1,5,1,0.5,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
...,...,...,...,...,...,...,...,...,...
17858,74,95,2,0.1,0,Wriddhiman Saha,Deepak Chahar,"Deepak Chahar to Wriddhiman Saha, no run,",0
17859,74,96,2,0.2,0,Wriddhiman Saha,Deepak Chahar,"Deepak Chahar to Wriddhiman Saha, no run,",0
17860,74,97,2,0.3,1,Wriddhiman Saha,Deepak Chahar,"Deepak Chahar to Wriddhiman Saha, 1 run,",1
17861,74,98,2,0.4,1,Shubman Gill,Deepak Chahar,"Deepak Chahar to Shubman Gill, 1 run,",1
17862,74,99,2,0.5,1,Wriddhiman Saha,Deepak Chahar,"Deepak Chahar to Wriddhiman Saha, 1 run,",1

In [6]:
for i in list(df.columns):
    print(f"{i}:{df[i].nunique()}")

match_no:74
ballnumber:136
inningno:2
over:120
outcome:23
batter:182
bowler:136
comment:9605
score:8

In [7]:
df.dtypes

match_no        int64
ballnumber      int64
inningno        int64
over          float64
outcome        object
batter         object
bowler         object
comment        object
score           int64
dtype: object

In [16]:
df['bowler'].unique()

array(['Mohammed Shami', 'Hardik Pandya', 'Josh Little', 'Rashid Khan',
       'Alzarri Joseph', 'Yash Dayal', 'Deepak Chahar',
       'Tushar Deshpande', 'Rajvardhan Hangargekar', 'Mitchell Santner',
       'Ravindra Jadeja', 'Umesh Yadav', 'Tim Southee', 'Sunil Narine',
       'Varun Chakravarthy', 'Shardul Thakur', 'Sam Curran',
       'Arshdeep Singh', 'Nathan Ellis', 'Sikandar Raza', 'Rishi Dhawan',
       'Rahul Chahar', 'Harpreet Brar', 'Khaleel Ahmed', 'Mukesh Kumar',
       'Chetan Sakariya', 'Axar Patel', 'Kuldeep Yadav', 'Kyle Mayers',
       'Jaydev Unadkat', 'Krishnappa Gowtham', 'Avesh Khan', 'Mark Wood',
       'Ravi Bishnoi', 'Bhuvneshwar Kumar', 'Fazalhaq Farooqi', 'Washing',
       'T Natarajan', 'Adil Rashid', 'Umran Malik', 'Trent Boult',
       'KM Asif', 'Jason Holder', 'Ravichandran Ashwin',
       'Yuzvendra Chahal', 'Navdeep Saini', 'Mohammed Siraj',
       'Reece Topley', 'Akash Deep', 'Harshal Patel', 'Karn Sharma',
       'Michael Bracewell', 'Glenn Maxwell', 'Jason Behrendorff',
       'Arshad Khan', 'Jofra Archer', 'Piyush Chawla', 'Cameron Green',
       'Hrithik Shokeen', 'Krunal Pandya', 'Yash Thakur', 'Ben S',
       'Moeen Ali', 'Anrich Nortje', 'Mitchell Marsh', 'David Willey',
       'Shahbaz Ahmed', 'Suyash Sharma', 'Deepak Hooda', 'Amit Mishra',
       'Aiden Markram', 'Rovman Powell', 'Sandeep Sharma',
       'Murugan Ashwin', 'Sisanda Magala', 'Dwaine Pre',
       'Kumar Kartikeya', 'Lockie Ferguson', 'Marco Jansen',
       'Mayank Markande', 'Mohit Rathee', 'Wayne Parnell',
       'Riley Meredith', 'Tilak Varma', 'Mustafizur Rahman',
       'Lalit Yadav', 'Akash Singh', 'Maheesh Theekshana', 'Kuldeep Sen',
       'Adam Zampa', 'Mohit Sharma', 'Kagiso Rabada', 'Matthew Short',
       'Andre Russell', 'Vijaykumar Vyshak', 'Wanindu Hasaranga',
       'Yudhvir Singh', 'Arjun Tendulkar', 'Duan Jansen', 'Noor Ahmad',
       'Matheesha Pathirana', 'Naveen-ul-Haq', 'Marcus S', 'Liam Livings',
       'Ishant Sharma', 'Kulwant Khejroliya', 'Anukul Roy', 'Nitish Rana',
       'Mayank Dagar', 'Jayant Yadav', 'Rahul Tewatia', 'David Wiese',
       'Vaibhav Arora', 'Kuldip Yadav', 'Gurnoor Brar', 'Ayush Badoni',
       'Harshit Rana', 'Akeal Hosein', 'Abhishek Sharma',
       'Josh Hazlewood', 'Mahipal Lomror', 'Akash Madhwal',
       'Kartik Tyagi', 'Raghav Goyal', 'Tristan Stubbs', 'Mohsin Khan',
       'Swapnil Singh', 'Vivrant Sharma', 'Obed McCoy', 'Chris Jordan',
       'Joe Root', 'Glenn Phillips', 'Praveen Dubey',
       'Nitish Kumar Reddy', 'Himanshu Sharma', 'Darshan Nalkande'],
      dtype=object)

In [14]:
df['Mohammed Shami']

KeyError: 'Mohammed Shami'